services:
  app:
    container_name: lv3-final-mission-app
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

  db:
    container_name: lv3-final-mission-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env.dev
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
