= Final Mission API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 개요

최종 미션 API 문서입니다.

== 인증 API


=== 멤버 로그인 API
`POST /auth/login`

- 로그인 요청을 보내고, 인증 쿠키(`token`)를 응답으로 받습니다.

operation::auth/member-login[snippets='http-request,request-fields,http-response,response-body']


=== 멤버 로그인 확인 API
`GET /auth/login/check`

- 요청자의 인증 상태를 확인하고, 로그인된 멤버의 이름을 반환합니다.

operation::auth/member-login-check[snippets='http-request,http-response,response-fields,response-body']


== 예약 API

=== 예약 목록 조회 API
`GET /bookings`

- 전체 예약 목록을 조회합니다. 관리자 또는 테스트 용도로 사용됩니다.

operation::reservation/find-all[snippets='http-request,http-response,response-fields,response-body']


== 멤버 예약 API


=== 예약 목록 조회 API
`GET /bookings/me`

- 로그인된 사용자의 예약 목록만 조회합니다.

operation::member-reservation/find-all[snippets='http-request,http-response,response-fields,response-body']


=== 예약 생성 API
`POST /bookings`

- 강의 ID를 지정해 예약을 생성합니다.

operation::member-reservation/create[snippets='http-request,request-fields,http-response,response-fields,response-body']


=== 예약 수정 API
`PUT /bookings/{id}`

- 지정한 예약 ID에 해당하는 예약의 예약 인원을 수정합니다.

operation::member-reservation/update[snippets='path-parameters,http-request,request-fields,http-response,response-fields,response-body']


=== 예약 삭제 API

`DELETE /bookings/{id}`

- 지정한 예약 ID에 해당하는 예약을 삭제합니다.

operation::member-reservation/delete[snippets='path-parameters,http-request,http-response,response-body']
